generation:
  num_subsamples: 5
  num_demos: 5
  num_prompts_per_subsample: 50
  model:
    name: Llama-2
    batch_size: 1
    gpt_config:
      model: text-davinci-002
      temperature: 1.0
      max_tokens: 50
      top_p: 1.0
      frequency_penalty: 0.0
      presence_penalty: 0.0
evaluation:
  method: likelihood
  num_samples: 50
  num_few_shot: 5
  model:
    name: Llama-2
    batch_size: 1
    gpt_config:
      model: text-davinci-002
      temperature: 1.0
      max_tokens: 200
      top_p: 1.0
      frequency_penalty: 0.0
      presence_penalty: 0.0
demo:
  model:
    name: Llama2Model
    batch_size: 2
    gpt_config:
      model: text-davinci-002
      temperature: 1.0
      max_tokens: 200
      top_p: 1.0
      frequency_penalty: 0.0
      presence_penalty: 0.0
